services:
    db:
        image: postgres:latest
        working_dir: /user
        volumes:
            - db-data:/user
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        ports:
            - "${DB_PORT}:5432"
        networks:
            - network_1

volumes:
    db-data:

networks:
    network_1:
        driver: bridge